package warnings;

XSLoader::load( 'Warnings' );

# Warning category offsets - used by experimental.pm to check if a warning exists
# These map warning category names to their bit positions
our %Offsets = (
    'all'				=> 0,
    'closure'				=> 2,
    'deprecated'			=> 4,
    'exiting'				=> 6,
    'glob'				=> 8,
    'io'				=> 10,
    'closed'				=> 12,
    'exec'				=> 14,
    'layer'				=> 16,
    'newline'				=> 18,
    'pipe'				=> 20,
    'unopened'				=> 22,
    'misc'				=> 24,
    'numeric'				=> 26,
    'once'				=> 28,
    'overflow'				=> 30,
    'pack'				=> 32,
    'portable'				=> 34,
    'recursion'				=> 36,
    'redefine'				=> 38,
    'regexp'				=> 40,
    'severe'				=> 42,
    'debugging'				=> 44,
    'inplace'				=> 46,
    'internal'				=> 48,
    'malloc'				=> 50,
    'signal'				=> 52,
    'substr'				=> 54,
    'syntax'				=> 56,
    'ambiguous'				=> 58,
    'bareword'				=> 60,
    'digit'				=> 62,
    'parenthesis'			=> 64,
    'precedence'			=> 66,
    'printf'				=> 68,
    'prototype'				=> 70,
    'qw'				=> 72,
    'reserved'				=> 74,
    'semicolon'				=> 76,
    'taint'				=> 78,
    'threads'				=> 80,
    'uninitialized'			=> 82,
    'unpack'				=> 84,
    'untie'				=> 86,
    'utf8'				=> 88,
    'void'				=> 90,
    'imprecision'			=> 92,
    'illegalproto'			=> 94,
    'deprecated::goto_construct'	=> 96,
    'deprecated::unicode_property_name'	=> 98,
    'non_unicode'			=> 100,
    'nonchar'				=> 102,
    'surrogate'				=> 104,
    'experimental'			=> 106,
    'experimental::regex_sets'		=> 108,
    'syscalls'				=> 110,
    'experimental::re_strict'		=> 112,
    'experimental::refaliasing'		=> 114,
    'locale'				=> 116,
    'missing'				=> 118,
    'redundant'				=> 120,
    'experimental::declared_refs'	=> 122,
    'deprecated::dot_in_inc'		=> 124,
    'shadow'				=> 126,
    'experimental::private_use'		=> 128,
    'experimental::uniprop_wildcards'	=> 130,
    'experimental::vlb'			=> 132,
    'experimental::try'			=> 134,
    'experimental::args_array_with_signatures'=> 136,
    'experimental::builtin'		=> 138,
    'experimental::defer'		=> 140,
    'experimental::extra_paired_delimiters'=> 142,
    'scalar'				=> 144,
    'deprecated::version_downgrade'	=> 146,
    'deprecated::delimiter_will_be_paired'=> 148,
    'experimental::class'		=> 150,
    'deprecated::missing_import_called_with_args'=> 152,
    'deprecated::subsequent_use_version'=> 154,
    'experimental::keyword_all'		=> 156,
    'experimental::keyword_any'		=> 158,
);

# NoOp warnings - warnings that have been removed but kept for compatibility
our %NoOp = ();

sub register_categories {
    # placeholder
}

1;
