use strict;
use warnings;
use Test::More;
use Cwd qw(getcwd);
use File::Path qw(make_path);
use File::Temp qw(tempdir);

my $orig_dir = getcwd();
my $tmpdir = tempdir(CLEANUP => 1);
END { chdir $orig_dir if defined $orig_dir }

chdir $tmpdir or die "chdir $tmpdir: $!";
make_path('lib/Local') or die "make_path lib/Local: $!";

open my $pod_pm, '>', 'lib/Local/PodOnly.pm' or die "create POD-only module: $!";
print {$pod_pm} "package Local::PodOnly;\n1;\n__END__\n=head1 NAME\n\nLocal::PodOnly\n\n=cut\n";
close $pod_pm or die "close POD-only module: $!";

open my $loader_pm, '>', 'lib/Local/Loader.pm' or die "create AutoLoader module: $!";
print {$loader_pm} "package Local::Loader;\nuse AutoLoader;\n1;\n__END__;\nsub deferred { 42 }\n";
close $loader_pm or die "close AutoLoader module: $!";

open my $makefile_pl, '>', 'Makefile.PL' or die "create Makefile.PL: $!";
print {$makefile_pl} "# generated by the unit test\n";
close $makefile_pl or die "close Makefile.PL: $!";

use ExtUtils::MakeMaker;
WriteMakefile(
    NAME => 'Local::AutosplitSelection', VERSION => '0.001',
    PM => {
        'lib/Local/PodOnly.pm' => '$(INST_LIB)/Local/PodOnly.pm',
        'lib/Local/Loader.pm'  => '$(INST_LIB)/Local/Loader.pm',
    },
);

open my $mf, '<', 'Makefile' or die "open generated Makefile: $!";
my $makefile = do { local $/; <$mf> };
close $mf or die "close generated Makefile: $!";

unlike($makefile, qr/autosplit\([^\n]+Local\/PodOnly\.pm/,
       'POD-only __END__ markers do not trigger AutoSplit');
ok($makefile =~ qr/autosplit\([^\n]+Local\/Loader\.pm/
       || $makefile =~ qr/pm_to_blib\(\{\@ARGV\}/,
   'modules using AutoLoader with __END__; remain covered by the staging rule');

my $status = system($ENV{MAKE} || 'make', 'pm_to_blib');
is($status, 0, 'AutoLoader module stages successfully');
ok(-f 'blib/lib/auto/Local/Loader/autosplit.ix',
   'AutoSplit accepts the __END__; marker');

done_testing();
