use strict;
use warnings;
use Test::More tests => 3;
use File::Temp qw(tempdir);
use Cwd qw(getcwd);

my $dir = tempdir(CLEANUP => 1);
my $cwd = getcwd();
chdir $dir or die "chdir $dir: $!";

open my $module, '>', 'CallbackStyle.pm' or die $!;
print {$module} "package CallbackStyle;\nour \$VERSION = '0.01';\n1;\n";
close $module;
open my $makefile_pl, '>', 'Makefile.PL' or die $!;
print {$makefile_pl} "# generated by regression test\n";
close $makefile_pl;

{
    package MY;
    sub postamble {
        return "\npm_to_blib: README\n\nconfig::\n\t\@true\n\nREADME: CallbackStyle.pm\n\t\@true\n";
    }
}

use ExtUtils::MakeMaker;
WriteMakefile(
    NAME         => 'CallbackStyle',
    VERSION_FROM => 'CallbackStyle.pm',
);

open my $makefile_fh, '<', 'Makefile' or die $!;
my $makefile = do { local $/; <$makefile_fh> };
close $makefile_fh;

my %styles;
while ($makefile =~ /^pm_to_blib\s*(::?)/mg) {
    $styles{$1}++;
}

is(scalar(keys %styles), 1, 'base and postamble pm_to_blib rules use one style');
unlike($makefile, qr/^config:::/m, 'existing double-colon postamble rule is unchanged');
ok(system($ENV{MAKE} || 'make', '-n', 'pm_to_blib') == 0,
    'generated pm_to_blib rules are accepted by make');

chdir $cwd or die "chdir $cwd: $!";
