package org.perlonjava;

import org.perlonjava.runtime.ErrorMessageUtil;
import org.perlonjava.runtime.GlobalVariable;
import org.perlonjava.runtime.RuntimeScalar;
import org.perlonjava.scriptengine.PerlLanguageProvider;

import java.util.Locale;

/**
 * The Main class serves as the entry point for the Perl-to-Java bytecode compiler and runtime
 * evaluator. It accepts the command-line arguments, parses Perl code, generates corresponding Java bytecode using ASM, and executes the
 * generated bytecode.
 */
public class Main {

    static {
        // Set default locale to US (uses dot as decimal separator)
        Locale.setDefault(Locale.US);
    }

    /**
     * The main method initializes the compilation and execution process.
     *
     * @param args Command-line arguments.
     */
    public static void main(String[] args) {
        CompilerOptions parsedArgs = ArgumentParser.parseArguments(args);

        if (parsedArgs.code == null) {
            System.err.println("No code provided. Use -e <code> or specify a filename.");
            System.exit(1);
        }

        try {
            PerlLanguageProvider.executePerlCode(parsedArgs, true);

            if (parsedArgs.compileOnly) {
                System.out.println(parsedArgs.fileName + " syntax OK");
            }

            // Match system perl behavior:
            // - Running external commands sets $? (usually as a wait status like 0x0200),
            //   but does NOT by itself make the perl interpreter exit non-zero.
            // - Test frameworks (Test2/Test::More) set $? to a small integer (1..255)
            //   in an END block to request a non-zero exit status.
            RuntimeScalar childStatus = GlobalVariable.getGlobalVariable("main::?");
            int rawChildStatus = childStatus.getInt();
            if (rawChildStatus > 0 && rawChildStatus <= 255) {
                System.exit(rawChildStatus);
            }
        } catch (Throwable t) {
            if (parsedArgs.debugEnabled) {
                // Print full JVM stack
                t.printStackTrace();
                System.out.println();
            }

            String errorMessage = ErrorMessageUtil.stringifyException(t);
            System.out.println(errorMessage);

            // Match system perl behavior for unhandled die:
            // Prefer $! (errno) if non-zero, else prefer ($? >> 8), else 255.
            int exitCode = 255;
            try {
                int bang = GlobalVariable.getGlobalVariable("main::!").getInt();
                int query = GlobalVariable.getGlobalVariable("main::?").getInt();
                int queryExit = (query >> 8);
                if (bang != 0) {
                    exitCode = bang;
                } else if (queryExit != 0) {
                    exitCode = queryExit;
                }
            } catch (Throwable ignored) {
                // Last resort below
            }

            System.exit(exitCode);
        }
    }

}

