package Devel::PPPort;

use strict;
use warnings;
use Exporter ();

our $VERSION = '3.68';
our @ISA = qw(Exporter);
our @EXPORT_OK = qw(GetFileContents WriteFile);

sub GetFileContents {
    return <<"END_PPPORT";
#ifndef PERLONJAVA_PPPORT_H
#define PERLONJAVA_PPPORT_H 1
/* Minimal ppport.h generated by PerlOnJava's Devel::PPPort shim. */
#endif
END_PPPORT
}

sub WriteFile {
    my $file = shift || 'ppport.h';
    open my $fh, '>', $file or return 0;
    print {$fh} GetFileContents();
    close $fh or return 0;
    return 1;
}

1;
