/*
 * Generated from the current Perl Unicode keyword table and Unicode property
 * alias tables. Do not edit manually.
 *
 * Unicode version: 17.0.0
 * Source: uni_keywords.h (SHA-256 ccbc1b09be7e393558d3a0ebbd1eb53d5ed1c5d7db6f04effca2977bb622432a)
 * Perl source notice: !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * Perl source notice: This file is built by regen/mk_invlists.pl from mph.pl.
 * Perl source notice: Any changes made here will be lost!
 *
 * Source: PropertyAliases.txt (SHA-256 4441f573caf952ffece1d7c892e7715bd7136dfc26f96eb6f268bf1e474715fb)
 * © 2025 Unicode®, Inc.
 * Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the U.S. and other countries.
 * For terms of use and license, see https://www.unicode.org/terms_of_use.html
 *
 * Source: PropValueAliases.txt (SHA-256 670d2bebb48649c04fabfbf033308073dcff47946324a8033237254c048b3b01)
 * © 2025 Unicode®, Inc.
 * Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the U.S. and other countries.
 * For terms of use and license, see https://www.unicode.org/terms_of_use.html
 *
 */
package org.perlonjava.runtime.regex;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

final class PerlUnicodeBinaryPropertyAliasData {
    static final String UNICODE_VERSION = "17.0.0";
    static final String PERL_KEYWORD_SHA256 = "ccbc1b09be7e393558d3a0ebbd1eb53d5ed1c5d7db6f04effca2977bb622432a";

    private static final String[] ACCEPTED = {
        "ahex", "ASCII_Hex_Digit", "alpha", "Alphabetic", "alphabetic", "Alphabetic",
        "asciihexdigit", "ASCII_Hex_Digit", "bidic", "Bidi_Control", "bidicontrol", "Bidi_Control",
        "bidim", "Bidi_Mirrored", "bidimirrored", "Bidi_Mirrored", "cased", "Cased",
        "caseignorable", "Case_Ignorable", "ce", "Composition_Exclusion", "changeswhencasefolded", "Changes_When_Casefolded",
        "changeswhencasemapped", "Changes_When_Casemapped", "changeswhenlowercased", "Changes_When_Lowercased", "changeswhennfkccasefolded", "Changes_When_NFKC_Casefolded",
        "changeswhentitlecased", "Changes_When_Titlecased", "changeswhenuppercased", "Changes_When_Uppercased", "ci", "Case_Ignorable",
        "compex", "Full_Composition_Exclusion", "compositionexclusion", "Composition_Exclusion", "cwcf", "Changes_When_Casefolded",
        "cwcm", "Changes_When_Casemapped", "cwkcf", "Changes_When_NFKC_Casefolded", "cwl", "Changes_When_Lowercased",
        "cwt", "Changes_When_Titlecased", "cwu", "Changes_When_Uppercased", "dash", "Dash",
        "defaultignorablecodepoint", "Default_Ignorable_Code_Point", "dep", "Deprecated", "deprecated", "Deprecated",
        "di", "Default_Ignorable_Code_Point", "dia", "Diacritic", "diacritic", "Diacritic",
        "ebase", "Emoji_Modifier_Base", "ecomp", "Emoji_Component", "emod", "Emoji_Modifier",
        "emoji", "Emoji", "emojicomponent", "Emoji_Component", "emojimodifier", "Emoji_Modifier",
        "emojimodifierbase", "Emoji_Modifier_Base", "emojipresentation", "Emoji_Presentation", "epres", "Emoji_Presentation",
        "ext", "Extender", "extendedpictographic", "Extended_Pictographic", "extender", "Extender",
        "extpict", "Extended_Pictographic", "fullcompositionexclusion", "Full_Composition_Exclusion", "graphemebase", "Grapheme_Base",
        "graphemeextend", "Grapheme_Extend", "grbase", "Grapheme_Base", "grext", "Grapheme_Extend",
        "hex", "Hex_Digit", "hexdigit", "Hex_Digit", "hyphen", "Hyphen",
        "idc", "ID_Continue", "idcompatmathcontinue", "ID_Compat_Math_Continue", "idcompatmathstart", "ID_Compat_Math_Start",
        "idcontinue", "ID_Continue", "ideo", "Ideographic", "ideographic", "Ideographic",
        "ids", "ID_Start", "idsb", "IDS_Binary_Operator", "idsbinaryoperator", "IDS_Binary_Operator",
        "idst", "IDS_Trinary_Operator", "idstart", "ID_Start", "idstrinaryoperator", "IDS_Trinary_Operator",
        "idsu", "IDS_Unary_Operator", "idsunaryoperator", "IDS_Unary_Operator", "joinc", "Join_Control",
        "joincontrol", "Join_Control", "kehnomirror", "kEH_NoMirror", "kehnorotate", "kEH_NoRotate",
        "loe", "Logical_Order_Exception", "logicalorderexception", "Logical_Order_Exception", "lower", "Lowercase",
        "lowercase", "Lowercase", "math", "Math", "mcm", "Modifier_Combining_Mark",
        "modifiercombiningmark", "Modifier_Combining_Mark", "nchar", "Noncharacter_Code_Point", "noncharactercodepoint", "Noncharacter_Code_Point",
        "patsyn", "Pattern_Syntax", "patternsyntax", "Pattern_Syntax", "patternwhitespace", "Pattern_White_Space",
        "patws", "Pattern_White_Space", "pcm", "Prepended_Concatenation_Mark", "prependedconcatenationmark", "Prepended_Concatenation_Mark",
        "qmark", "Quotation_Mark", "quotationmark", "Quotation_Mark", "radical", "Radical",
        "regionalindicator", "Regional_Indicator", "ri", "Regional_Indicator", "sd", "Soft_Dotted",
        "sentenceterminal", "Sentence_Terminal", "softdotted", "Soft_Dotted", "space", "White_Space",
        "sterm", "Sentence_Terminal", "term", "Terminal_Punctuation", "terminalpunctuation", "Terminal_Punctuation",
        "uideo", "Unified_Ideograph", "unifiedideograph", "Unified_Ideograph", "upper", "Uppercase",
        "uppercase", "Uppercase", "variationselector", "Variation_Selector", "vs", "Variation_Selector",
        "whitespace", "White_Space", "wspace", "White_Space", "xidc", "XID_Continue",
        "xidcontinue", "XID_Continue", "xids", "XID_Start", "xidstart", "XID_Start",
    };

    private static final Set<String> REJECTED = Set.of(
        "expandsonnfc", "expandsonnfd", "expandsonnfkc", "expandsonnfkd", "graphemelink", "grlink",
        "nfdqc", "nfdquickcheck", "nfkdqc", "nfkdquickcheck", "oalpha", "odi",
        "ogrext", "oidc", "oids", "olower", "omath", "otheralphabetic",
        "otherdefaultignorablecodepoint", "othergraphemeextend", "otheridcontinue", "otheridstart", "otherlowercase", "othermath",
        "otheruppercase", "oupper", "xidcont", "xonfc", "xonfd", "xonfkc",
        "xonfkd"
    );

    private static final Map<String, String> ACCEPTED_BY_ALIAS = buildAccepted();

    static String canonicalProperty(String alias) {
        String normalized = normalize(alias);
        String canonical = ACCEPTED_BY_ALIAS.get(normalized);
        if (canonical == null && normalized.startsWith("is")) {
            canonical = ACCEPTED_BY_ALIAS.get(normalized.substring(2));
        }
        return canonical;
    }

    static boolean isRejected(String alias) {
        return REJECTED.contains(normalize(alias));
    }

    private static Map<String, String> buildAccepted() {
        Map<String, String> result = new HashMap<>();
        for (int i = 0; i < ACCEPTED.length; i += 2) {
            result.put(ACCEPTED[i], ACCEPTED[i + 1]);
        }
        return Map.copyOf(result);
    }

    private static String normalize(String value) {
        return value.toLowerCase(java.util.Locale.ROOT)
                .replaceAll("[\\x09-\\x0d _-]+", "");
    }

    private PerlUnicodeBinaryPropertyAliasData() {}
}
