#!/usr/bin/env perl
# Script to generate a Perl test file with a very large subroutine
# This is used to test the interpreter fallback mechanism

use strict;
use warnings;

my $num_statements = $ARGV[0] || 10000;
my $output_file = $ARGV[1] || "large_sub_test.pl";

open my $fh, '>', $output_file or die "Cannot open $output_file: $!";

print $fh "# Test file with large subroutine ($num_statements statements)\n";
print $fh "# Generated by gen_large_sub_test.pl\n\n";
print $fh "print \"1..2\\n\";\n\n";
print $fh "sub large_sub {\n";
print $fh "    my \$sum = 0;\n";

for my $i (1..$num_statements) {
    print $fh "    \$sum += $i;\n";
}

print $fh "    return \$sum;\n";
print $fh "}\n\n";

# Calculate expected sum: sum of 1 to n = n*(n+1)/2
my $expected = $num_statements * ($num_statements + 1) / 2;

print $fh "my \$result = large_sub();\n";
print $fh "print \"not \" unless \$result == $expected;\n";
print $fh "print \"ok 1 - large subroutine computed correct sum\\n\";\n\n";
print $fh "print \"not \" unless defined(&large_sub);\n";
print $fh "print \"ok 2 - large subroutine is defined\\n\";\n";

close $fh;

print "Generated $output_file with $num_statements statements\n";
print "Expected sum: $expected\n";
