#!/usr/bin/env perl
use strict;
use warnings;
use File::Spec;
use FindBin;
use lib File::Spec->catdir($FindBin::Bin, 'lib');
use PerlOnJava::UnicodeGenerator qw(
    read_pinned_source read_unicode_version repo_root select_unicode_root
    verify_unicode_notice
);

my $expected_unicode_version = '17.0.0';
my $version_hash = '8c30575264b2772c7a69c5bb6069a28f0e0a7a0df735871bde2d99ee674316ac';
my $sentence_hash = '871c0c985ad95125e25b302414065a10839d068970bceb383ecec138f22a0a18';
my $root = repo_root($FindBin::Bin);
my $unicode_root = select_unicode_root(
    repo_root => $root,
    version => $expected_unicode_version,
    required => ['version', 'auxiliary/SentenceBreakProperty.txt'],
);
my $unicode_version = read_unicode_version(
    path => File::Spec->catfile($unicode_root, 'version'),
    expected => $expected_unicode_version,
    sha256 => $version_hash,
);

my $property_path = File::Spec->catfile(
    $unicode_root, 'auxiliary', 'SentenceBreakProperty.txt');
my $property_text = read_pinned_source(
    path => $property_path,
    sha256 => $sentence_hash,
    version_pattern => qr/^# SentenceBreakProperty-\Q$expected_unicode_version\E\.txt$/m,
    unicode_version => $expected_unicode_version,
);
verify_unicode_notice($property_path, $property_text);
my @ranges;
for my $line (split /\n/, $property_text) {
    next unless $line =~ /^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Za-z_]+)/;
    push @ranges, [hex($1), defined($2) ? hex($2) : hex($1), $3];
}
@ranges = sort { $a->[0] <=> $b->[0] } @ranges;

my (@starts, @values);
my $cursor = 0;
for my $range (@ranges) {
    my ($start, $end, $property) = @$range;
    die "Overlapping Sentence_Break ranges at U+", sprintf('%04X', $start), "\n"
        if $start < $cursor;
    if ($start > $cursor) {
        push @starts, $cursor;
        push @values, 'Other';
    }
    push @starts, $start;
    push @values, $property;
    $cursor = $end + 1;
}
if ($cursor <= 0x10ffff) {
    push @starts, $cursor;
    push @values, 'Other';
}

my @classes = qw(
    Other ATerm Close CR Extend Format LF Lower Numeric OLetter SContinue Sep Sp STerm Upper
);
my %class_id;
@class_id{@classes} = (0 .. $#classes);

for my $value (@values) {
    die "Unknown Sentence_Break value '$value'\n" unless exists $class_id{$value};
}

print <<'HEADER';
/*
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Unicode data source:
 * SentenceBreakProperty-17.0.0.txt
 * SHA-256: 871c0c985ad95125e25b302414065a10839d068970bceb383ecec138f22a0a18
 * © 2025 Unicode®, Inc.
 * Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the
 * U.S. and other countries.
 * For terms of use and license, see https://www.unicode.org/terms_of_use.html
 */
package org.joni;

// Generated by dev/tools/generate_joni_boundary_data.pl. Do not edit manually.
final class SentenceBreakData {
HEADER

print "    static final String UNICODE_VERSION = \"$unicode_version\";\n";
print "    static final String SENTENCE_BREAK_SHA256 = \"$sentence_hash\";\n";
for my $i (0 .. $#classes) {
    my $constant = uc($classes[$i]);
    print "    static final byte $constant = $i;\n";
}

print "\n    private static final int[] STARTS = {\n";
for (my $i = 0; $i < @starts; $i += 10) {
    my $end = $i + 9 < $#starts ? $i + 9 : $#starts;
    print "        ", join(', ', map { sprintf '0x%X', $starts[$_] } $i .. $end), ",\n";
}
print "    };\n\n    private static final byte[] VALUES = {\n";
for (my $i = 0; $i < @values; $i += 16) {
    my $end = $i + 15 < $#values ? $i + 15 : $#values;
    print "        ", join(', ', map { uc($values[$_]) } $i .. $end), ",\n";
}
print <<'FOOTER';
    };

    static byte propertyOf(int codePoint) {
        int low = 0;
        int high = STARTS.length - 1;
        while (low <= high) {
            int middle = (low + high) >>> 1;
            if (STARTS[middle] <= codePoint) {
                low = middle + 1;
            } else {
                high = middle - 1;
            }
        }
        return VALUES[Math.max(0, high)];
    }

    private SentenceBreakData() {
    }
}
FOOTER
