#!/usr/bin/env perl
use strict;
use warnings;

my $unicode_root = 'perl5/lib/unicore';
my $expected_unicode_version = '17.0.0';
open my $version_fh, '<', "$unicode_root/version" or die "Can't read Unicode version: $!\n";
chomp(my $unicode_version = <$version_fh>);
close $version_fh;
die "Expected Unicode $expected_unicode_version, found $unicode_version\n"
    unless $unicode_version eq $expected_unicode_version;

open my $property_fh, '<', "$unicode_root/auxiliary/SentenceBreakProperty.txt"
    or die "Can't read Sentence_Break data: $!\n";
my @ranges;
while (<$property_fh>) {
    next unless /^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Za-z_]+)/;
    push @ranges, [hex($1), defined($2) ? hex($2) : hex($1), $3];
}
close $property_fh;
@ranges = sort { $a->[0] <=> $b->[0] } @ranges;

my (@starts, @values);
my $cursor = 0;
for my $range (@ranges) {
    my ($start, $end, $property) = @$range;
    die "Overlapping Sentence_Break ranges at U+", sprintf('%04X', $start), "\n"
        if $start < $cursor;
    if ($start > $cursor) {
        push @starts, $cursor;
        push @values, 'Other';
    }
    push @starts, $start;
    push @values, $property;
    $cursor = $end + 1;
}
if ($cursor <= 0x10ffff) {
    push @starts, $cursor;
    push @values, 'Other';
}

my @classes = qw(
    Other ATerm Close CR Extend Format LF Lower Numeric OLetter SContinue Sep Sp STerm Upper
);
my %class_id;
@class_id{@classes} = (0 .. $#classes);

for my $value (@values) {
    die "Unknown Sentence_Break value '$value'\n" unless exists $class_id{$value};
}

print <<'HEADER';
/*
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.joni;

// Generated by dev/tools/generate_joni_boundary_data.pl. Do not edit manually.
final class SentenceBreakData {
HEADER

print "    static final String UNICODE_VERSION = \"$unicode_version\";\n";
for my $i (0 .. $#classes) {
    my $constant = uc($classes[$i]);
    print "    static final byte $constant = $i;\n";
}

print "\n    private static final int[] STARTS = {\n";
for (my $i = 0; $i < @starts; $i += 10) {
    my $end = $i + 9 < $#starts ? $i + 9 : $#starts;
    print "        ", join(', ', map { sprintf '0x%X', $starts[$_] } $i .. $end), ",\n";
}
print "    };\n\n    private static final byte[] VALUES = {\n";
for (my $i = 0; $i < @values; $i += 16) {
    my $end = $i + 15 < $#values ? $i + 15 : $#values;
    print "        ", join(', ', map { uc($values[$_]) } $i .. $end), ",\n";
}
print <<'FOOTER';
    };

    static byte propertyOf(int codePoint) {
        int low = 0;
        int high = STARTS.length - 1;
        while (low <= high) {
            int middle = (low + high) >>> 1;
            if (STARTS[middle] <= codePoint) {
                low = middle + 1;
            } else {
                high = middle - 1;
            }
        }
        return VALUES[Math.max(0, high)];
    }

    private SentenceBreakData() {
    }
}
FOOTER
