#!/usr/bin/env perl
use strict;
use warnings;

my $unicode_root = 'perl5/lib/unicore';
my $expected_unicode_version = '17.0.0';
open my $version_fh, '<', "$unicode_root/version" or die "Can't read Unicode version: $!\n";
chomp(my $unicode_version = <$version_fh>);
close $version_fh;
die "Expected Unicode $expected_unicode_version, found $unicode_version\n"
    unless $unicode_version eq $expected_unicode_version;

sub read_property_ranges {
    my ($path, $wanted_property) = @_;
    open my $fh, '<', $path or die "Can't read $path: $!\n";
    my @ranges;
    while (<$fh>) {
        next unless /^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Za-z_]+)/;
        my ($start, $end, $property) = (hex($1), defined($2) ? hex($2) : hex($1), $3);
        next if defined($wanted_property) && $property ne $wanted_property;
        push @ranges, [$start, $end, $property];
    }
    close $fh;
    return sort { $a->[0] <=> $b->[0] } @ranges;
}

my @word_ranges = read_property_ranges("$unicode_root/auxiliary/WordBreakProperty.txt");
my (@starts, @values);
my $cursor = 0;
for my $range (@word_ranges) {
    my ($start, $end, $property) = @$range;
    die "Overlapping Word_Break ranges at U+", sprintf('%04X', $start), "\n"
        if $start < $cursor;
    if ($start > $cursor) {
        push @starts, $cursor;
        push @values, 'Other';
    }
    push @starts, $start;
    push @values, $property;
    $cursor = $end + 1;
}
if ($cursor <= 0x10ffff) {
    push @starts, $cursor;
    push @values, 'Other';
}

my @pictographic_ranges = read_property_ranges(
    "$unicode_root/emoji/emoji.txt", 'Extended_Pictographic');

my @classes = qw(
    Other ALetter CR Double_Quote Extend ExtendNumLet Format Hebrew_Letter
    Katakana LF MidLetter MidNum MidNumLet Newline Numeric Regional_Indicator
    Single_Quote WSegSpace ZWJ
);
my %class_id;
@class_id{@classes} = (0 .. $#classes);

for my $value (@values) {
    die "Unknown Word_Break value '$value'\n" unless exists $class_id{$value};
}

sub constant_name {
    my ($name) = @_;
    $name =~ s/([a-z])([A-Z])/$1_$2/g;
    return uc $name;
}

print <<'HEADER';
/*
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.joni;

// Generated by dev/tools/generate_joni_word_break_data.pl. Do not edit manually.
final class WordBreakData {
HEADER

print "    static final String UNICODE_VERSION = \"$unicode_version\";\n";
for my $i (0 .. $#classes) {
    print "    static final byte ", constant_name($classes[$i]), " = $i;\n";
}

print "\n    private static final int[] STARTS = {\n";
for (my $i = 0; $i < @starts; $i += 10) {
    my $end = $i + 9 < $#starts ? $i + 9 : $#starts;
    print "        ", join(', ', map { sprintf '0x%X', $starts[$_] } $i .. $end), ",\n";
}
print "    };\n\n    private static final byte[] VALUES = {\n";
for (my $i = 0; $i < @values; $i += 16) {
    my $end = $i + 15 < $#values ? $i + 15 : $#values;
    print "        ", join(', ', map { constant_name($values[$_]) } $i .. $end), ",\n";
}
print "    };\n\n    private static final int[] EXTENDED_PICTOGRAPHIC_RANGES = {\n";
my @pictographic_pairs = map { ($_->[0], $_->[1]) } @pictographic_ranges;
for (my $i = 0; $i < @pictographic_pairs; $i += 8) {
    my $end = $i + 7 < $#pictographic_pairs ? $i + 7 : $#pictographic_pairs;
    print "        ", join(', ', map { sprintf '0x%X', $pictographic_pairs[$_] } $i .. $end), ",\n";
}
print <<'FOOTER';
    };

    static byte propertyOf(int codePoint) {
        int low = 0;
        int high = STARTS.length - 1;
        while (low <= high) {
            int middle = (low + high) >>> 1;
            if (STARTS[middle] <= codePoint) {
                low = middle + 1;
            } else {
                high = middle - 1;
            }
        }
        return VALUES[Math.max(0, high)];
    }

    static boolean isExtendedPictographic(int codePoint) {
        int low = 0;
        int high = EXTENDED_PICTOGRAPHIC_RANGES.length / 2 - 1;
        while (low <= high) {
            int middle = (low + high) >>> 1;
            int start = EXTENDED_PICTOGRAPHIC_RANGES[middle * 2];
            int rangeEnd = EXTENDED_PICTOGRAPHIC_RANGES[middle * 2 + 1];
            if (codePoint < start) {
                high = middle - 1;
            } else if (codePoint > rangeEnd) {
                low = middle + 1;
            } else {
                return true;
            }
        }
        return false;
    }

    private WordBreakData() {
    }
}
FOOTER
