#!/usr/bin/env perl
use strict;
use warnings;
use Digest::SHA qw(sha256_hex);
use File::Spec;
use FindBin;
use lib File::Spec->catdir($FindBin::Bin, 'lib');
use PerlOnJava::UnicodeGenerator qw(
    emit_unicode_source_notices loose_name read_raw repo_root select_perl_root
    select_unicode_root trim verify_unicode_notice
);

my $root = repo_root($FindBin::Bin);
if (defined $ENV{PERLONJAVA_UNICODE_ROOT}) {
    for my $required (qw(version PropertyAliases.txt PropValueAliases.txt)) {
        my $path = File::Spec->catfile($ENV{PERLONJAVA_UNICODE_ROOT}, $required);
        die "Explicit Unicode source root missing $required\n" unless -f $path;
    }
}
my $unicore = select_unicode_root(
    repo_root => $root, version => 'current',
    required => [qw(version PropertyAliases.txt PropValueAliases.txt)],
);
if (defined $ENV{PERLONJAVA_PERL_ROOT}) {
    my $path = File::Spec->catfile($ENV{PERLONJAVA_PERL_ROOT}, 'uni_keywords.h');
    die "Explicit Perl source root missing uni_keywords.h\n" unless -f $path;
}
my $perl_root = select_perl_root(
    repo_root => $root, unicode_root => $unicore,
    required => ['uni_keywords.h'],
);

my $unicode_version = read_raw(File::Spec->catfile($unicore, 'version'));
$unicode_version =~ s/\s+\z//;
die "Malformed current Unicode version '$unicode_version'\n"
    unless $unicode_version =~ /\A\d+\.\d+\.\d+\z/;

my @unicode_sources = (
    ['PropertyAliases.txt', qr/^# PropertyAliases-\Q$unicode_version\E\.txt$/m],
    ['PropValueAliases.txt', qr/^# PropertyValueAliases-\Q$unicode_version\E\.txt$/m],
);
for my $source (@unicode_sources) {
    my ($name, $version_pattern) = @$source;
    my $path = File::Spec->catfile($unicore, $name);
    my $text = read_raw($path);
    die "$path is inconsistent with Unicode $unicode_version\n"
        unless $text =~ $version_pattern;
    verify_unicode_notice($path, $text);
    @$source = ($name, sha256_hex($text), $text);
}
my %unicode_text = map { $_->[0] => $_->[2] } @unicode_sources;

my $keyword_path = File::Spec->catfile($perl_root, 'uni_keywords.h');
my $keyword_text = read_raw($keyword_path);
die "$keyword_path is not a generated Perl Unicode keyword table\n"
    unless $keyword_text =~ m{^/\* -\*- mode: C; buffer-read-only: t -\*-\n}
        && $keyword_text =~ /^ \* !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!$/m
        && $keyword_text =~ /^ \* This file is built by regen\/mk_invlists\.pl from mph\.pl\.$/m
        && $keyword_text =~ /^ \* Any changes made here will be lost!$/m;

my %keyword;
for my $line (split /\n/, $keyword_text) {
    next unless $line =~ m{/\* ([a-z0-9_=.+-]+) \*/};
    die "$keyword_path repeats normalized keyword '$1'\n" if $keyword{$1}++;
}
die "$keyword_path contains no generated Unicode keywords\n" unless %keyword;

my %property_aliases;
for my $line (split /\n/, $unicode_text{'PropertyAliases.txt'}) {
    $line =~ s/\s*#.*\z//;
    next unless $line =~ /\S/;
    my @field = map { trim($_) } split /;/, $line;
    die "Malformed PropertyAliases row '$line'\n" unless @field >= 2;
    die "PropertyAliases repeats '$field[0]'\n" if exists $property_aliases{$field[0]};
    $property_aliases{$field[0]} = \@field;
}

my %value_names;
for my $line (split /\n/, $unicode_text{'PropValueAliases.txt'}) {
    $line =~ s/\s*#.*\z//;
    next unless $line =~ /\S/;
    my @field = map { trim($_) } split /;/, $line;
    die "Malformed PropValueAliases row '$line'\n" unless @field >= 3;
    $value_names{$field[0]}{loose_name($field[1])} = 1;
}

my %bare_only_enumerated_property = map { $_ => 1 } qw(NFD_QC NFKD_QC);
my (%accepted, %rejected, %bare_only_enumerated);
for my $property (sort keys %property_aliases) {
    my $values = $value_names{$property} // next;
    next unless keys(%$values) == 2 && $values->{n} && $values->{y};
    my $aliases = $property_aliases{$property};
    if ($bare_only_enumerated_property{$property}) {
        for my $spelling (@$aliases) {
            next unless length $spelling;
            $bare_only_enumerated{loose_name($spelling)} = 1;
        }
        next;
    }
    my $canonical = $aliases->[1];
    for my $spelling (@$aliases) {
        next unless length $spelling;
        my $loose = loose_name($spelling);
        if ($keyword{$loose}) {
            die "Conflicting accepted binary alias '$loose'\n"
                if exists $accepted{$loose} && $accepted{$loose} ne $canonical;
            $accepted{$loose} = $canonical;
        } else {
            $rejected{$loose} = 1;
        }
    }
}
die "No Perl binary property aliases found\n" unless %accepted;
die "Current Perl keywords omit XIDC\n"
    unless $accepted{xidc} && $accepted{xidcontinue};

# PerlOnJava historically accepted this non-Unicode abbreviation.  Its absence
# from the current generated Perl keyword table is an intentional rejection.
die "Current Perl unexpectedly accepts the compatibility spelling xidcont\n"
    if $keyword{xidcont};
$rejected{xidcont} = 1;
delete $rejected{$_} for keys %accepted;

my @accepted = sort keys %accepted;
my @rejected = sort keys %rejected;
my @bare_only_enumerated = sort keys %bare_only_enumerated;
my $keyword_hash = sha256_hex($keyword_text);

print <<'HEADER';
/*
 * Generated from the current Perl Unicode keyword table and Unicode property
 * alias tables. Do not edit manually.
 *
HEADER
print " * Unicode version: $unicode_version\n";
print " * Source: uni_keywords.h (SHA-256 $keyword_hash)\n";
print " * Perl source notice: !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!\n";
print " * Perl source notice: This file is built by regen/mk_invlists.pl from mph.pl.\n";
print " * Perl source notice: Any changes made here will be lost!\n";
print " *\n";
emit_unicode_source_notices([
    map { +{name => "$_->[0] (SHA-256 $_->[1])", text => $_->[2]} }
        @unicode_sources
]);
print <<'HEADER';
 */
package org.perlonjava.runtime.regex;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

final class PerlUnicodeBinaryPropertyAliasData {
HEADER
print "    static final String UNICODE_VERSION = \"$unicode_version\";\n";
print "    static final String PERL_KEYWORD_SHA256 = \"$keyword_hash\";\n\n";
print "    private static final String[] ACCEPTED = {\n";
for (my $index = 0; $index < @accepted; $index += 3) {
    my $last = $index + 2 < $#accepted ? $index + 2 : $#accepted;
    print "        ", join(', ', map {
        qq{\"$accepted[$_]\", \"$accepted{$accepted[$_]}\"}
    } $index .. $last), ",\n";
}
print "    };\n\n";
print "    private static final Set<String> REJECTED = Set.of(\n";
for (my $index = 0; $index < @rejected; $index += 6) {
    my $last = $index + 5 < $#rejected ? $index + 5 : $#rejected;
    my $suffix = $last == $#rejected ? '' : ',';
    print "        ", join(', ', map { qq{\"$rejected[$_]\"} }
        $index .. $last), "$suffix\n";
}
print "    );\n\n";
print "    private static final Set<String> BARE_ONLY_ENUMERATED = Set.of(\n";
for (my $index = 0; $index < @bare_only_enumerated; $index += 6) {
    my $last = $index + 5 < $#bare_only_enumerated
        ? $index + 5 : $#bare_only_enumerated;
    my $suffix = $last == $#bare_only_enumerated ? '' : ',';
    print "        ", join(', ', map { qq{"$bare_only_enumerated[$_]"} }
        $index .. $last), "$suffix\n";
}
print <<'FOOTER';
    );

    private static final Map<String, String> ACCEPTED_BY_ALIAS = buildAccepted();

    static String canonicalProperty(String alias) {
        String normalized = normalize(alias);
        String canonical = ACCEPTED_BY_ALIAS.get(normalized);
        if (canonical == null && normalized.startsWith("is")) {
            canonical = ACCEPTED_BY_ALIAS.get(normalized.substring(2));
        }
        return canonical;
    }

    static boolean isRejected(String alias) {
        return REJECTED.contains(normalize(alias));
    }

    static boolean isBareOnlyEnumerated(String alias) {
        return BARE_ONLY_ENUMERATED.contains(normalize(alias));
    }

    private static Map<String, String> buildAccepted() {
        Map<String, String> result = new HashMap<>();
        for (int i = 0; i < ACCEPTED.length; i += 2) {
            result.put(ACCEPTED[i], ACCEPTED[i + 1]);
        }
        return Map.copyOf(result);
    }

    private static String normalize(String value) {
        return value.toLowerCase(java.util.Locale.ROOT)
                .replaceAll("[\\x09-\\x0d _-]+", "");
    }

    private PerlUnicodeBinaryPropertyAliasData() {}
}
FOOTER
