#!/usr/bin/env perl
use strict;
use warnings;
use File::Spec;
use FindBin;
use lib File::Spec->catdir($FindBin::Bin, 'lib');
use PerlOnJava::UnicodeGenerator qw(
    read_pinned_source read_unicode_version repo_root select_unicode_root
    verify_unicode_notice
);

my $expected_unicode_version = '17.0.0';
my $version_hash = '8c30575264b2772c7a69c5bb6069a28f0e0a7a0df735871bde2d99ee674316ac';
my %source_hash = (
    'auxiliary/WordBreakProperty.txt' =>
        '72274cac1e6b919507db35655c3e175aa27274668a1ece95c28d2069f2ad9852',
    'emoji/emoji.txt' =>
        '2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b',
);
my $root = repo_root($FindBin::Bin);
my $unicode_root = select_unicode_root(
    repo_root => $root,
    version => $expected_unicode_version,
    required => ['version', sort keys %source_hash],
);
my $unicode_version = read_unicode_version(
    path => File::Spec->catfile($unicode_root, 'version'),
    expected => $expected_unicode_version,
    sha256 => $version_hash,
);
my %source_text;
for my $relative (sort keys %source_hash) {
    my $path = File::Spec->catfile($unicode_root, split m{/}, $relative);
    $source_text{$relative} = read_pinned_source(
        path => $path, sha256 => $source_hash{$relative});
    verify_unicode_notice($path, $source_text{$relative});
}
die "WordBreakProperty.txt is not pinned Unicode $expected_unicode_version data\n"
    unless $source_text{'auxiliary/WordBreakProperty.txt'}
        =~ /^# WordBreakProperty-\Q$expected_unicode_version\E\.txt$/m;
die "emoji.txt is not pinned Unicode $expected_unicode_version data\n"
    unless $source_text{'emoji/emoji.txt'} =~ /^# Version: 17\.0$/m;

sub read_property_ranges {
    my ($text, $wanted_property) = @_;
    my @ranges;
    for my $line (split /\n/, $text) {
        next unless $line =~ /^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Za-z_]+)/;
        my ($start, $end, $property) = (hex($1), defined($2) ? hex($2) : hex($1), $3);
        next if defined($wanted_property) && $property ne $wanted_property;
        push @ranges, [$start, $end, $property];
    }
    return sort { $a->[0] <=> $b->[0] } @ranges;
}

my @word_ranges = read_property_ranges(
    $source_text{'auxiliary/WordBreakProperty.txt'});
my (@starts, @values);
my $cursor = 0;
for my $range (@word_ranges) {
    my ($start, $end, $property) = @$range;
    die "Overlapping Word_Break ranges at U+", sprintf('%04X', $start), "\n"
        if $start < $cursor;
    if ($start > $cursor) {
        push @starts, $cursor;
        push @values, 'Other';
    }
    push @starts, $start;
    push @values, $property;
    $cursor = $end + 1;
}
if ($cursor <= 0x10ffff) {
    push @starts, $cursor;
    push @values, 'Other';
}

my @pictographic_ranges = read_property_ranges(
    $source_text{'emoji/emoji.txt'}, 'Extended_Pictographic');

my @classes = qw(
    Other ALetter CR Double_Quote Extend ExtendNumLet Format Hebrew_Letter
    Katakana LF MidLetter MidNum MidNumLet Newline Numeric Regional_Indicator
    Single_Quote WSegSpace ZWJ
);
my %class_id;
@class_id{@classes} = (0 .. $#classes);

for my $value (@values) {
    die "Unknown Word_Break value '$value'\n" unless exists $class_id{$value};
}

sub constant_name {
    my ($name) = @_;
    $name =~ s/([a-z])([A-Z])/$1_$2/g;
    return uc $name;
}

print <<'HEADER';
/*
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Unicode data sources:
 * WordBreakProperty-17.0.0.txt
 * SHA-256: 72274cac1e6b919507db35655c3e175aa27274668a1ece95c28d2069f2ad9852
 * emoji-17.0.txt
 * SHA-256: 2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b
 * © 2025 Unicode®, Inc.
 * Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the
 * U.S. and other countries.
 * For terms of use and license, see https://www.unicode.org/terms_of_use.html
 */
package org.joni;

// Generated by dev/tools/generate_joni_word_break_data.pl. Do not edit manually.
final class WordBreakData {
HEADER

print "    static final String UNICODE_VERSION = \"$unicode_version\";\n";
print "    static final String WORD_BREAK_SHA256 = \"$source_hash{'auxiliary/WordBreakProperty.txt'}\";\n";
print "    static final String EMOJI_SHA256 = \"$source_hash{'emoji/emoji.txt'}\";\n";
for my $i (0 .. $#classes) {
    print "    static final byte ", constant_name($classes[$i]), " = $i;\n";
}

print "\n    private static final int[] STARTS = {\n";
for (my $i = 0; $i < @starts; $i += 10) {
    my $end = $i + 9 < $#starts ? $i + 9 : $#starts;
    print "        ", join(', ', map { sprintf '0x%X', $starts[$_] } $i .. $end), ",\n";
}
print "    };\n\n    private static final byte[] VALUES = {\n";
for (my $i = 0; $i < @values; $i += 16) {
    my $end = $i + 15 < $#values ? $i + 15 : $#values;
    print "        ", join(', ', map { constant_name($values[$_]) } $i .. $end), ",\n";
}
print "    };\n\n    private static final int[] EXTENDED_PICTOGRAPHIC_RANGES = {\n";
my @pictographic_pairs = map { ($_->[0], $_->[1]) } @pictographic_ranges;
for (my $i = 0; $i < @pictographic_pairs; $i += 8) {
    my $end = $i + 7 < $#pictographic_pairs ? $i + 7 : $#pictographic_pairs;
    print "        ", join(', ', map { sprintf '0x%X', $pictographic_pairs[$_] } $i .. $end), ",\n";
}
print <<'FOOTER';
    };

    static byte propertyOf(int codePoint) {
        int low = 0;
        int high = STARTS.length - 1;
        while (low <= high) {
            int middle = (low + high) >>> 1;
            if (STARTS[middle] <= codePoint) {
                low = middle + 1;
            } else {
                high = middle - 1;
            }
        }
        return VALUES[Math.max(0, high)];
    }

    static boolean isExtendedPictographic(int codePoint) {
        int low = 0;
        int high = EXTENDED_PICTOGRAPHIC_RANGES.length / 2 - 1;
        while (low <= high) {
            int middle = (low + high) >>> 1;
            int start = EXTENDED_PICTOGRAPHIC_RANGES[middle * 2];
            int rangeEnd = EXTENDED_PICTOGRAPHIC_RANGES[middle * 2 + 1];
            if (codePoint < start) {
                high = middle - 1;
            } else if (codePoint > rangeEnd) {
                low = middle + 1;
            } else {
                return true;
            }
        }
        return false;
    }

    private WordBreakData() {
    }
}
FOOTER
