#!/usr/bin/env perl
use strict;
use warnings;
use Unicode::UCD qw(prop_invmap);

my $expected_version = '16.0.0';
die "Unicode $expected_version is required (found " . Unicode::UCD::UnicodeVersion() . ")\n"
    unless Unicode::UCD::UnicodeVersion() eq $expected_version;

my @classes = qw(
    AI AK AL AP AS B2 BA BB BK CB CJ CL CM CP CR EB EM EX GL H2 H3 HH HL HY
    ID IN IS JL JT JV LF NL NS NU OP PO PR QU RI SA SG SP SY VF VI WJ XX ZW ZWJ
);
my %class_id;
@class_id{@classes} = (0 .. $#classes);

my %maps;
for my $property (qw(Line_Break General_Category East_Asian_Width Extended_Pictographic)) {
    my ($starts, $values) = prop_invmap($property);
    die "$property inversion map is unavailable\n" unless $starts && $values;
    $maps{$property} = [$starts, $values];
}

my %starts;
for my $map (values %maps) {
    $starts{$_} = 1 for grep { $_ <= 0x10ffff } @{$map->[0]};
}
my @starts = sort { $a <=> $b } keys %starts;

sub value_at {
    my ($map, $code) = @_;
    my ($starts, $values) = @$map;
    my ($low, $high) = (0, $#$starts);
    while ($low <= $high) {
        my $middle = ($low + $high) >> 1;
        if ($starts->[$middle] <= $code) {
            $low = $middle + 1;
        } else {
            $high = $middle - 1;
        }
    }
    return $values->[$high < 0 ? 0 : $high];
}

my @values;
for my $code (@starts) {
    my $lb = value_at($maps{Line_Break}, $code);
    my $gc = value_at($maps{General_Category}, $code);
    my $ea = value_at($maps{East_Asian_Width}, $code);
    my $ep = value_at($maps{Extended_Pictographic}, $code);

    $lb = 'AL' if $lb eq 'AI' || $lb eq 'SG' || $lb eq 'XX';
    $lb = $gc eq 'Mn' || $gc eq 'Mc' ? 'CM' : 'AL' if $lb eq 'SA';
    $lb = 'NS' if $lb eq 'CJ';
    die "Unknown Line_Break value '$lb'\n" unless exists $class_id{$lb};

    my $packed = $class_id{$lb};
    $packed |= 1 << 6 if $gc eq 'Pi';
    $packed |= 1 << 7 if $gc eq 'Pf';
    $packed |= 1 << 8 if $ea eq 'F' || $ea eq 'W' || $ea eq 'H';
    $packed |= 1 << 9 if $ep eq 'Y' && $gc eq 'Cn';
    push @values, $packed;
}

# Coalesce adjacent union intervals whose packed value is identical.
my (@coalesced_starts, @coalesced_values);
for my $i (0 .. $#starts) {
    next if @coalesced_values && $values[$i] == $coalesced_values[-1];
    push @coalesced_starts, $starts[$i];
    push @coalesced_values, $values[$i];
}

print <<'HEADER';
/*
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.joni;

// Generated by dev/tools/generate_joni_line_break_data.pl. Do not edit manually.
final class LineBreakData {
HEADER

print "    static final String UNICODE_VERSION = \"$expected_version\";\n";
for my $class (@classes) {
    print "    static final short $class = $class_id{$class};\n";
}
print <<'FLAGS';
    static final short CLASS_MASK = 0x3f;
    static final short INITIAL_PUNCTUATION = 1 << 6;
    static final short FINAL_PUNCTUATION = 1 << 7;
    static final short EAST_ASIAN = 1 << 8;
    static final short UNASSIGNED_EXTENDED_PICTOGRAPHIC = 1 << 9;

FLAGS

print "    private static final int[] STARTS = {\n";
for (my $i = 0; $i < @coalesced_starts; $i += 10) {
    my $end = $i + 9 < $#coalesced_starts ? $i + 9 : $#coalesced_starts;
    print "        ", join(', ', map { sprintf '0x%X', $coalesced_starts[$_] } $i .. $end), ",\n";
}
print "    };\n\n    private static final short[] VALUES = {\n";
for (my $i = 0; $i < @coalesced_values; $i += 16) {
    my $end = $i + 15 < $#coalesced_values ? $i + 15 : $#coalesced_values;
    print "        ", join(', ', @coalesced_values[$i .. $end]), ",\n";
}
print <<'FOOTER';
    };

    static short propertyOf(int codePoint) {
        int low = 0;
        int high = STARTS.length - 1;
        while (low <= high) {
            int middle = (low + high) >>> 1;
            if (STARTS[middle] <= codePoint) {
                low = middle + 1;
            } else {
                high = middle - 1;
            }
        }
        return VALUES[Math.max(0, high)];
    }

    static short lineClass(short property) {
        return (short)(property & CLASS_MASK);
    }

    static boolean has(short property, short flag) {
        return (property & flag) != 0;
    }

    private LineBreakData() {
    }
}
FOOTER
