use strict;
use warnings;
use File::Path qw(make_path);
use File::Spec;
use File::Temp qw(tempdir);
use FindBin;
use IPC::Open3;
use Symbol qw(gensym);
use Test::More;

my $repo = File::Spec->rel2abs(File::Spec->catdir($FindBin::Bin, '..', '..', '..'));
my $generator = File::Spec->catfile(
    $repo, 'dev', 'tools', 'generate_perl_unicode_binary_property_alias_data.pl');
my $temporary = tempdir(CLEANUP => 1);
my $unicode = File::Spec->catdir($temporary, 'unicore');
my $perl_root = File::Spec->catdir($temporary, 'perl5');
make_path($unicode, $perl_root);

write_sources();
my ($status, $first) = run_generator();
is($status, 0, 'generator accepts complete current Unicode and Perl sources');
like($first, qr/"xidc", "XID_Continue"/,
    'accepted XID short alias is generated from current Perl keywords');
like($first, qr/"xidcontinue", "XID_Continue"/,
    'accepted XID long alias is generated from current Perl keywords');
like($first, qr/"graphemelink".*"grlink".*"xidcont"/s,
    'current Perl omissions and compatibility spelling are explicit rejections');
my ($second_status, $second) = run_generator();
is($second_status, 0, 'second generation succeeds');
is($second, $first, 'generation is byte-for-byte deterministic');

my $keywords = File::Spec->catfile($perl_root, 'uni_keywords.h');
my $valid_keywords = read_file($keywords);
unlink $keywords or die "Cannot remove $keywords: $!";
my ($missing_status, $missing_log) = run_generator();
isnt($missing_status, 0, 'generator rejects a missing Perl keyword source');
like($missing_log, qr/Explicit Perl source root missing uni_keywords\.h/,
    'missing Perl source has a focused diagnostic');

write_file($keywords, "/* not a generated table */\n");
my ($header_status, $header_log) = run_generator();
isnt($header_status, 0, 'generator rejects malformed Perl source provenance');
like($header_log, qr/not a generated Perl Unicode keyword table/,
    'malformed Perl provenance has a focused diagnostic');
write_file($keywords, $valid_keywords);

my $aliases = File::Spec->catfile($unicode, 'PropertyAliases.txt');
my $valid_aliases = read_file($aliases);
write_file($aliases, $valid_aliases . "MalformedRow\n");
my ($row_status, $row_log) = run_generator();
isnt($row_status, 0, 'generator rejects malformed Unicode property rows');
like($row_log, qr/Malformed PropertyAliases row 'MalformedRow'/,
    'malformed Unicode row has a focused diagnostic');

done_testing;

sub notice {
    return "# © 2025 Unicode®, Inc.\n"
        . "# Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the U.S. and other countries.\n"
        . "# For terms of use and license, see https://www.unicode.org/terms_of_use.html\n";
}

sub write_sources {
    write_file(File::Spec->catfile($unicode, 'version'), "18.0.0\n");
    write_file(File::Spec->catfile($unicode, 'PropertyAliases.txt'),
        "# PropertyAliases-18.0.0.txt\n" . notice()
        . "AHex ; ASCII_Hex_Digit\nGr_Link ; Grapheme_Link\n"
        . "XIDC ; XID_Continue\n");
    write_file(File::Spec->catfile($unicode, 'PropValueAliases.txt'),
        "# PropertyValueAliases-18.0.0.txt\n" . notice()
        . "AHex ; N ; No ; F ; False\nAHex ; Y ; Yes ; T ; True\n"
        . "Gr_Link ; N ; No ; F ; False\nGr_Link ; Y ; Yes ; T ; True\n"
        . "XIDC ; N ; No ; F ; False\nXIDC ; Y ; Yes ; T ; True\n");
    write_file(File::Spec->catfile($perl_root, 'uni_keywords.h'), <<'KEYWORDS');
/* -*- mode: C; buffer-read-only: t -*-
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * This file is built by regen/mk_invlists.pl from mph.pl.
 * Any changes made here will be lost!
 */
  { 0 } /* ahex */,
  { 0 } /* asciihexdigit */,
  { 0 } /* isahex */,
  { 0 } /* isasciihexdigit */,
  { 0 } /* isxidc */,
  { 0 } /* isxidcontinue */,
  { 0 } /* xidc */,
  { 0 } /* xidcontinue */,
KEYWORDS
}

sub run_generator {
    local %ENV = %ENV;
    $ENV{PERLONJAVA_UNICODE_ROOT} = $unicode;
    $ENV{PERLONJAVA_PERL_ROOT} = $perl_root;
    my $error = gensym;
    my $pid = open3(undef, my $stdout, $error, $^X, $generator);
    local $/;
    my $bytes = (<$stdout> // '') . (<$error> // '');
    waitpid($pid, 0);
    return ($? >> 8, $bytes);
}

sub write_file {
    my ($path, $bytes) = @_;
    open my $output, '>:raw', $path or die "Cannot write $path: $!";
    print {$output} $bytes or die "Cannot write $path: $!";
    close $output or die "Cannot close $path: $!";
}

sub read_file {
    my ($path) = @_;
    open my $input, '<:raw', $path or die "Cannot read $path: $!";
    local $/;
    my $bytes = <$input>;
    close $input or die "Cannot close $path: $!";
    return $bytes;
}
