#!/usr/bin/env perl
use strict;
use warnings;
use Digest::SHA qw(sha256_hex);
use File::Spec;
use FindBin;
use lib File::Spec->catdir($FindBin::Bin, 'lib');
use PerlOnJava::UnicodeGenerator qw(
    emit_unicode_source_notices parse_range read_pinned_source read_raw repo_root select_unicode_root
    verify_unicode_notice
);

my $root = repo_root($FindBin::Bin);
my $expected_hash = '09c928886a178fcafd93c29e4bd59073a058e5a100b716d425cb563ab50f68c9';
my $unicode_root = select_unicode_root(
    repo_root => $root, version => 'current', required => ['version', 'DCoreProperties.txt'],
);
my $version = read_raw(File::Spec->catfile($unicode_root, 'version'));
$version =~ s/\s+\z//;
die "Malformed Unicode version '$version'\n" unless $version =~ /\A\d+\.\d+\.\d+\z/;
my $path = File::Spec->catfile($unicode_root, 'DCoreProperties.txt');
my $text = read_pinned_source(path => $path, sha256 => $expected_hash);
verify_unicode_notice($path, $text);
die "$path is inconsistent with Unicode $version\n"
    unless $text =~ /^# DerivedCoreProperties-\Q$version\E\.txt$/m;
my $hash = sha256_hex($text);

my %kind = (None => 0, Consonant => 1, Extend => 2, Linker => 4);
my @properties = (0) x 0x110000;
for my $line (split /\n/, $text) {
    next unless $line =~ /^([0-9A-F]+(?:\.\.[0-9A-F]+)?)\s*;\s*InCB\s*;\s*(Consonant|Extend|Linker)\b/;
    my ($start, $end) = parse_range($1);
    $properties[$_] |= $kind{$2} for $start .. $end;
}
my (@starts, @values);
my ($start, $value) = (0, $properties[0]);
for my $code (1 .. 0x10FFFF) {
    next if $properties[$code] == $value;
    push @starts, $start; push @values, $value;
    ($start, $value) = ($code, $properties[$code]);
}
push @starts, $start; push @values, $value;

print <<'HEADER';
/*
 * Generated from the current Perl checkout's Unicode Character Database. Do not edit manually.
 *
HEADER
emit_unicode_source_notices([{ name => 'DCoreProperties.txt', text => $text }]);
print <<'JAVA';
 */
package org.joni;

import org.joni.ast.CClassNode;

// Generated by dev/regex/tools/generate_joni_indic_conjunct_data.pl. Do not edit manually.
final class IndicConjunctData {
JAVA
print "    static final String UNICODE_VERSION = \"$version\";\n";
print "    static final String DCORE_PROPERTIES_SHA256 = \"$hash\";\n";
print "    static final byte NONE = 0;\n    static final byte CONSONANT = 1;\n";
print "    static final byte EXTEND = 2;\n    static final byte LINKER = 4;\n\n";
print "    private static final int[] STARTS = {\n";
for (my $i = 0; $i < @starts; $i += 12) {
    my $end = $i + 11 < $#starts ? $i + 11 : $#starts;
    print '        ', join(', ', map { sprintf '0x%X', $starts[$_] } $i .. $end), ",\n";
}
print "    };\n\n    private static final byte[] VALUES = {\n";
for (my $i = 0; $i < @values; $i += 24) {
    my $end = $i + 23 < $#values ? $i + 23 : $#values;
    print '        ', join(', ', @values[$i .. $end]), ",\n";
}
print <<'FOOTER';
    };

    static void addTo(CClassNode characterClass, ScanEnvironment environment, byte value) {
        for (int index = 0; index < VALUES.length; index++) {
            if ((VALUES[index] & value) == 0) continue;
            int start = STARTS[index];
            int end = index + 1 < STARTS.length ? STARTS[index + 1] - 1 : 0x10FFFF;
            characterClass.addCodeRange(environment, start, end);
        }
    }

    static byte propertyOf(int codePoint) {
        int low = 0;
        int high = STARTS.length - 1;
        while (low <= high) {
            int middle = (low + high) >>> 1;
            if (STARTS[middle] <= codePoint) low = middle + 1;
            else high = middle - 1;
        }
        return VALUES[Math.max(0, high)];
    }

    private IndicConjunctData() {
    }
}
FOOTER
