#!/usr/bin/env perl
use strict;
use warnings;
use Digest::SHA qw(sha256_hex);
use Encode qw(encode);
use File::Spec;
use FindBin;
use MIME::Base64 qw(encode_base64);

# Unicode data source copyright:
# © 2025 Unicode®, Inc.
# Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in
# the U.S. and other countries.
# For terms of use and license, see https://www.unicode.org/terms_of_use.html

my $repo_root = File::Spec->rel2abs(File::Spec->catdir($FindBin::Bin, '..', '..', '..'));
my $source = $ENV{PERLONJAVA_NAME_PL}
        // File::Spec->catfile($repo_root, 'src', 'main', 'perl', 'lib', 'unicore', 'Name.pl');
open my $source_fh, '<:raw', $source or die "Cannot read $source: $!\n";
local $/;
my $source_text = <$source_fh>;
close $source_fh or die "Cannot close $source: $!\n";
my $source_sha256 = sha256_hex($source_text);
$source_text =~ /return <<'END';\r?\n(.*)\r?\nEND\r?\n?\z/s
        or die "$source does not have the expected generated Name.pl format\n";
my $records = $1;
$records =~ s/\r\n/\n/g;

my (%first_code_point, @duplicate_names);
for my $record (split /\n\n/, $records) {
    my ($code_points, $name, @extra) = split /\n/, $record;
    die "Malformed Name.pl record: $record\n"
            if !defined $name || @extra || !length $name;
    next if $code_points =~ /\s/; # Multi-code-point sequences have a separate owner.
    die "Invalid scalar code point '$code_points' for '$name'\n"
            unless $code_points =~ /\A[0-9A-F]{5,6}\z/;
    die "Non-ASCII or tab character in scalar name '$name'\n"
            unless $name =~ /\A[\x20-\x7E]+\z/ && $name !~ /\t/;
    if (exists $first_code_point{$name}) {
        push @duplicate_names, $name;
        next; # Match Name.pl's anchored search: the first name row wins.
    }
    $first_code_point{$name} = hex $code_points;
}

my @names = sort keys %first_code_point;
die "Name.pl contains no scalar names\n" unless @names;
my $binary = encode_varint(scalar @names);
my $previous = '';
for my $name (@names) {
    my $prefix_length = common_prefix_length($previous, $name);
    my $suffix = substr($name, $prefix_length);
    $binary .= encode_varint($prefix_length)
            . encode_varint(length $suffix)
            . encode_varint($first_code_point{$name})
            . encode('ASCII', $suffix);
    $previous = $name;
}
my $encoded = encode_base64($binary, '');
my @chunks = $encoded =~ /.{1,8000}/g;

print <<'HEADER';
/*
 * Generated from the current imported Perl unicore/Name.pl.
 * Do not edit manually; run dev/regex/tools/generate_perl_unicode_scalar_name_data.pl.
 *
 * Name.pl is generated by Perl's mktables from the Unicode Character Database.
 * Duplicate-name policy matches Perl's anchored table search: the first row wins.
 * Distinct names for the same code point are all retained as Unicode aliases.
 *
 * Unicode data source copyright:
 * © 2025 Unicode®, Inc.
 * Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in
 * the U.S. and other countries.
 * For terms of use and license, see https://www.unicode.org/terms_of_use.html
 */
package org.perlonjava.runtime.regex;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Base64;

public final class PerlUnicodeScalarNameData {
HEADER
print "    public static final String SOURCE_SHA256 = \"$source_sha256\";\n";
print "    public static final int ENTRY_COUNT = ", scalar(@names), ";\n";
print "    public static final int DUPLICATE_NAME_COUNT = ", scalar(@duplicate_names), ";\n\n";
print "    private static final String[] ENCODED = {\n";
print qq{        "$_",\n} for @chunks;
print <<'FOOTER';
    };

    private static final String[] NAMES;
    private static final int[] CODE_POINTS;

    static {
        byte[] data = Base64.getDecoder().decode(String.join("", ENCODED));
        Cursor cursor = new Cursor();
        int count = readVarint(data, cursor);
        if (count != ENTRY_COUNT) {
            throw new IllegalStateException("Invalid generated Perl scalar-name count: " + count);
        }
        NAMES = new String[count];
        CODE_POINTS = new int[count];
        String previous = "";
        for (int index = 0; index < count; index++) {
            int prefixLength = readVarint(data, cursor);
            int suffixLength = readVarint(data, cursor);
            int codePoint = readVarint(data, cursor);
            if (prefixLength > previous.length()
                    || suffixLength > data.length - cursor.offset) {
                throw new IllegalStateException("Invalid generated Perl scalar-name data");
            }
            String suffix = new String(
                    data, cursor.offset, suffixLength, StandardCharsets.US_ASCII);
            cursor.offset += suffixLength;
            String name = previous.substring(0, prefixLength) + suffix;
            NAMES[index] = name;
            CODE_POINTS[index] = codePoint;
            previous = name;
        }
        if (cursor.offset != data.length) {
            throw new IllegalStateException("Trailing generated Perl scalar-name data");
        }
    }

    public static int codePoint(String name) {
        if (name == null) return -1;
        int index = Arrays.binarySearch(NAMES, name);
        return index < 0 ? -1 : CODE_POINTS[index];
    }

    static int entryCount() {
        return NAMES.length;
    }

    private static int readVarint(byte[] data, Cursor cursor) {
        int value = 0;
        int shift = 0;
        while (cursor.offset < data.length && shift < 35) {
            int current = data[cursor.offset++] & 0xff;
            value |= (current & 0x7f) << shift;
            if ((current & 0x80) == 0) return value;
            shift += 7;
        }
        throw new IllegalStateException("Invalid generated Perl scalar-name varint");
    }

    private static final class Cursor {
        private int offset;
    }

    private PerlUnicodeScalarNameData() {
    }
}
FOOTER

sub common_prefix_length {
    my ($left, $right) = @_;
    my $limit = length($left) < length($right) ? length($left) : length($right);
    my $offset = 0;
    $offset++ while $offset < $limit
            && substr($left, $offset, 1) eq substr($right, $offset, 1);
    return $offset;
}

sub encode_varint {
    my ($value) = @_;
    my $encoded = '';
    while ($value >= 0x80) {
        $encoded .= chr(($value & 0x7f) | 0x80);
        $value >>= 7;
    }
    return $encoded . chr($value);
}
