package org.perlonjava.app.cli;

import org.perlonjava.app.scriptengine.PerlLanguageProvider;
import org.perlonjava.runtime.runtimetypes.ErrorMessageUtil;
import org.perlonjava.runtime.runtimetypes.GlobalVariable;
import org.perlonjava.runtime.runtimetypes.PerlExitException;
import org.perlonjava.runtime.runtimetypes.RuntimeScalar;

import java.util.Locale;

/**
 * The Main class serves as the entry point for the Perl-to-Java bytecode compiler and runtime
 * evaluator. It accepts the command-line arguments, parses Perl code, generates corresponding Java bytecode using ASM, and executes the
 * generated bytecode.
 */
public class Main {

    static {
        // Set default locale to US (uses dot as decimal separator)
        Locale.setDefault(Locale.US);

        // Optional orphan-exit watchdog. When the env var
        // JPERL_ORPHAN_EXIT is set (typically by `./jcpan` and
        // `./jprove`, which spawn many short-lived sub-jperls), this
        // JVM self-exits a few seconds after its initial parent
        // process disappears. Without this, a `kill -9` on the parent
        // jcpan/test_harness leaves all in-flight test JVMs reparented
        // to PID 1, where they happily keep running at 100% CPU
        // forever — burning the box and starving subsequent runs.
        //
        // SIGTERM-style parent death is already handled by the
        // shutdown hook in RuntimeIO; this watchdog covers the SIGKILL
        // case (no shutdown hooks fire on the kernel-side kill).
        //
        // Direct `./jperl your_script.pl` does NOT set the env var, so
        // user programs are never killed when their shell exits — they
        // get the standard nohup-style behavior they'd expect from any
        // long-running interpreter.
        if (System.getenv("JPERL_ORPHAN_EXIT") != null) {
            startOrphanWatchdog();
        }
    }

    private static void startOrphanWatchdog() {
        java.util.Optional<java.lang.ProcessHandle> parentOpt =
                java.lang.ProcessHandle.current().parent();
        if (parentOpt.isEmpty()) return;       // no parent? nothing to watch.
        long initialParentPid = parentOpt.get().pid();
        // PID 1 = init/launchd. If we were directly spawned by it,
        // there's no point watching — we're already at the root.
        if (initialParentPid <= 1) return;

        Thread watchdog = new Thread(() -> {
            // Poll every 2s. Exit only after two consecutive misses
            // (~4s) to avoid race with rapid parent restarts.
            int missCount = 0;
            while (true) {
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ie) {
                    return;
                }
                java.util.Optional<java.lang.ProcessHandle> p =
                        java.lang.ProcessHandle.of(initialParentPid);
                boolean parentGone = p.isEmpty() || !p.get().isAlive();
                if (parentGone) {
                    if (++missCount >= 2) {
                        System.err.println("[jperl] orphaned: parent PID "
                                + initialParentPid
                                + " is gone — exiting");
                        Runtime.getRuntime().halt(143);  // 128 + SIGTERM
                    }
                } else {
                    missCount = 0;
                }
            }
        }, "perlonjava-orphan-watchdog");
        watchdog.setDaemon(true);
        watchdog.start();
    }

    /**
     * The main method initializes the compilation and execution process.
     *
     * @param args Command-line arguments.
     */
    public static void main(String[] args) {
        CompilerOptions parsedArgs = ArgumentParser.parseArguments(args);

        if (parsedArgs.code == null) {
            System.err.println("No code provided. Use -e <code> or specify a filename.");
            System.exit(1);
        }

        try {
            PerlLanguageProvider.executePerlCode(parsedArgs, true);

            if (parsedArgs.compileOnly) {
                System.out.println(parsedArgs.fileName + " syntax OK");
            }

            // Match system perl behavior:
            // - Running external commands sets $? (usually as a wait status like 0x0200),
            //   but does NOT by itself make the perl interpreter exit non-zero.
            // - Test frameworks (Test2/Test::More) set $? to a small integer (1..255)
            //   in an END block to request a non-zero exit status.
            RuntimeScalar childStatus = GlobalVariable.getGlobalVariable("main::?");
            int rawChildStatus = childStatus.getInt();
            if (rawChildStatus > 0 && rawChildStatus <= 255) {
                System.exit(rawChildStatus);
            }
        } catch (PerlExitException e) {
            // Perl's exit() throws PerlExitException - convert to real System.exit() for CLI
            System.exit(e.getExitCode());
        } catch (Throwable t) {
            if (parsedArgs.debugEnabled) {
                // Print full JVM stack
                t.printStackTrace();
                System.out.println();
            }

            String errorMessage = ErrorMessageUtil.stringifyException(t);
            System.err.print(errorMessage);

            // Match system perl behavior for unhandled die:
            // Prefer $! (errno) if non-zero, else prefer ($? >> 8), else 255.
            int exitCode = 255;
            try {
                int bang = GlobalVariable.getGlobalVariable("main::!").getInt();
                int query = GlobalVariable.getGlobalVariable("main::?").getInt();
                int queryExit = (query >> 8);
                if (bang != 0) {
                    exitCode = bang;
                } else if (queryExit != 0) {
                    exitCode = queryExit;
                }
            } catch (Throwable ignored) {
                // Last resort below
            }

            System.exit(exitCode);
        }
    }

}

