package org.perlonjava.runtime.perlmodule;

import org.perlonjava.runtime.runtimetypes.*;

import static org.perlonjava.runtime.runtimetypes.RuntimeScalarType.*;

/**
 * Java built-in for overload::StrVal and overload::AddrRef.
 *
 * <p>These must bypass overloaded stringification to avoid infinite recursion.
 * In Perl 5, overload::AddrRef uses {@code no overloading; "$_[0]"} to get the raw
 * "Class=TYPE(0xADDR)" string without triggering the overloaded {@code ""} operator.
 * Since PerlOnJava does not yet implement the {@code no overloading} pragma, we provide
 * Java built-ins that call toStringRef() directly.
 */
public class OverloadModule extends PerlModuleBase {

    public OverloadModule() {
        // false: don't set %INC — overload.pm is loaded from the .pm file
        super("overload", false);
    }

    public static void initialize() {
        OverloadModule mod = new OverloadModule();
        try {
            mod.registerMethod("StrVal", "$");
            mod.registerMethod("AddrRef", "$");
            mod.registerMethod("__poj_const_call", null);
        } catch (NoSuchMethodException e) {
            System.err.println("Warning: Missing overload method: " + e.getMessage());
        }
    }

    /**
     * overload::StrVal($obj) — returns the raw "Class=TYPE(0xADDR)" string
     * WITHOUT triggering overloaded "" operator.
     */
    public static RuntimeList StrVal(RuntimeArray args, int ctx) {
        if (args.size() != 1) {
            throw new IllegalStateException("Bad number of arguments for overload::StrVal");
        }
        RuntimeScalar scalar = args.get(0);

        return switch (scalar.type) {
            case REFERENCE -> new RuntimeScalar(scalar.toStringRef()).getList();
            case ARRAYREFERENCE, HASHREFERENCE, CODE, GLOB, GLOBREFERENCE, FORMAT, REGEX ->
                    new RuntimeScalar(((RuntimeBase) scalar.value).toStringRef()).getList();
            default ->
                    // For non-references, return the raw string value
                    new RuntimeScalar(scalar.toStringRef()).getList();
        };
    }

    /**
     * overload::AddrRef is an alias for StrVal.
     */
    public static RuntimeList AddrRef(RuntimeArray args, int ctx) {
        return StrVal(args, ctx);
    }

    /**
     * Internal helper used by {@code NumberParser.wrapWithConstantHandler()} to
     * invoke an {@code overload::constant} handler while guarding against
     * re-entry.
     * <p>
     * Arguments (all positional): {@code ($handler, $text, $num, $category)}.
     * <p>
     * Temporarily removes {@code %^H{$category}} for the duration of the
     * handler's execution. This matches Perl's semantics whereby a
     * {@code :constant} handler is not re-invoked for literals that the
     * handler's own body compiles via {@code eval STRING} — without this,
     * patterns like {@code sub { return eval $_[0] }} in
     * {@code overload::constant float => ...} would infinite-recurse.
     * <p>
     * Invoked from parse-emitted AST, so the generated bytecode for a
     * numeric literal is effectively:
     * <pre>
     *   overload::__poj_const_call($handler, $text, $num, $category)
     * </pre>
     * instead of the raw {@code $handler-&gt;($text, $num, $category)} call.
     */
    public static RuntimeList __poj_const_call(RuntimeArray args, int ctx) {
        if (args.size() != 4) {
            throw new IllegalStateException(
                    "Bad number of arguments for overload::__poj_const_call (got "
                            + args.size() + ", want 4)");
        }
        RuntimeScalar handler = args.get(0);
        RuntimeScalar text = args.get(1);
        RuntimeScalar num = args.get(2);
        RuntimeScalar category = args.get(3);

        // Temporarily remove %^H{category} so that any eval STRING executed
        // by the handler does not recursively re-wrap the same literal.
        String hhKey = Character.toString('H' - 'A' + 1);                 // "\cH"
        String hashName = "main::" + hhKey;
        RuntimeHash hh = GlobalVariable.getGlobalHash(hashName);
        String catKey = category.toString();
        RuntimeScalar saved = hh.elements.remove(catKey);

        try {
            RuntimeArray callArgs = new RuntimeArray();
            callArgs.elements.add(text);
            callArgs.elements.add(num);
            callArgs.elements.add(category);
            return RuntimeCode.apply(handler, callArgs, ctx);
        } finally {
            if (saved != null) {
                hh.elements.put(catKey, saved);
            }
        }
    }
}
