package org.perlonjava.runtime.perlmodule;
import org.perlonjava.runtime.operators.ReferenceOperators;import org.perlonjava.runtime.runtimetypes.*;import java.util.*;
/** Java trigram index compatible with Search::Trigram's public API. */
public class SearchTrigram extends PerlModuleBase{
 public static final String XS_VERSION="0.02";public SearchTrigram(){super("Search::Trigram",false);}public static void initialize(){SearchTrigram m=new SearchTrigram();try{m.registerMethod("new","construct",null);for(String n:new String[]{"add","search","remove","optimize","clear","doc_count","trigram_count","_abi_ptr","_abi_version","_abi_selftest","_abi_selftest_add","_abi_selftest_doc_count"})m.registerMethod(n,null);}catch(Exception e){throw new IllegalStateException(e);}}
 private static final class Index{int next;Map<Integer,String> docs=new LinkedHashMap<>();Set<Integer> deleted=new HashSet<>();}
 private static Index idx(RuntimeScalar s){return (Index)s.hashDeref().get("_java_index").value;}
 public static RuntimeList construct(RuntimeArray a,int c){RuntimeHash h=new RuntimeHash();h.put("_java_index",new RuntimeScalar(new Index()));return ReferenceOperators.bless(h.createReferenceWithTrackedElements(),new RuntimeScalar("Search::Trigram")).getList();}
 public static RuntimeList add(RuntimeArray a,int c){Index x=idx(a.get(0));int id=x.next++;x.docs.put(id,a.get(1).toString());return new RuntimeScalar(id).getList();}
 private static Set<String> tri(String s){Set<String>r=new HashSet<>();s=s.toLowerCase(Locale.ROOT);for(int i=0;i+3<=s.length();i++)r.add(s.substring(i,i+3));return r;}
 public static RuntimeList search(RuntimeArray a,int c){Index x=idx(a.get(0));Set<String>q=tri(a.get(1).toString());int lim=a.size()>2?a.get(2).getInt():10;record Hit(int id,double score,String text){}List<Hit>hs=new ArrayList<>();for(var e:x.docs.entrySet()){if(x.deleted.contains(e.getKey()))continue;Set<String>d=tri(e.getValue());int n=0;for(String t:q)if(d.contains(t))n++;if(n>0)hs.add(new Hit(e.getKey(),2.0*n/(q.size()+d.size()),e.getValue()));}hs.sort((u,v)->Double.compare(v.score,u.score));RuntimeArray out=new RuntimeArray();for(int i=0;i<Math.min(lim,hs.size());i++){Hit z=hs.get(i);RuntimeHash h=new RuntimeHash();h.put("doc_id",new RuntimeScalar(z.id));h.put("score",new RuntimeScalar(z.score));h.put("text",new RuntimeScalar(z.text));RuntimeArray.push(out,h.createAnonymousReference());}return out.createAnonymousReference().getList();}
 public static RuntimeList remove(RuntimeArray a,int c){idx(a.get(0)).deleted.add(a.get(1).getInt());return new RuntimeList();}public static RuntimeList optimize(RuntimeArray a,int c){Index x=idx(a.get(0));for(int id:x.deleted)x.docs.remove(id);x.deleted.clear();return new RuntimeList();}public static RuntimeList clear(RuntimeArray a,int c){Index x=idx(a.get(0));x.docs.clear();x.deleted.clear();x.next=0;return new RuntimeList();}public static RuntimeList doc_count(RuntimeArray a,int c){Index x=idx(a.get(0));return new RuntimeScalar(x.docs.size()-x.deleted.size()).getList();}public static RuntimeList trigram_count(RuntimeArray a,int c){Index x=idx(a.get(0));Set<String>s=new HashSet<>();for(var e:x.docs.entrySet())if(!x.deleted.contains(e.getKey()))s.addAll(tri(e.getValue()));return new RuntimeScalar(s.size()).getList();}
 public static RuntimeList _abi_ptr(RuntimeArray a,int c){return new RuntimeScalar(1).getList();}public static RuntimeList _abi_version(RuntimeArray a,int c){return new RuntimeScalar(1).getList();}public static RuntimeList _abi_selftest_add(RuntimeArray a,int c){if(!valid(a.get(0)))return new RuntimeList();return add(a,c);}public static RuntimeList _abi_selftest_doc_count(RuntimeArray a,int c){if(!valid(a.get(0)))return new RuntimeList();return doc_count(a,c);}public static RuntimeList _abi_selftest(RuntimeArray a,int c){if(!valid(a.get(0)))return new RuntimeList();RuntimeList wrapped=search(a,c);return wrapped.scalar().arrayDeref().getList();}private static boolean valid(RuntimeScalar s){return s.type==RuntimeScalarType.HASHREFERENCE&&s.hashDeref().get("_java_index").value instanceof Index;}
}
